version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 8

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 8

  - package-ecosystem: npm
    directory: /widget-loader
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 4

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
