<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Equine.Jobs</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Equine.Domain\Equine.Domain.csproj" />
    <ProjectReference Include="..\Equine.Infrastructure\Equine.Infrastructure.csproj" />
  </ItemGroup>

</Project>
