@Equine.Api_HostAddress = http://localhost:5087

GET {{Equine.Api_HostAddress}}/health
Accept: application/json

###

GET {{Equine.Api_HostAddress}}/health/ready
Accept: application/json

###

GET {{Equine.Api_HostAddress}}/api/public/ping
Accept: application/json

###
